"""Chimera-aware pangenomic distributions.

Same as get_pan_distrs.py but with the addition of chimeric genes and their
multi-family membership.
Reads .gene_parents (vertical lineage) generated by get_gene_parents.py
and .chimeras.csv and generate multi-membership family files:
a chimeric gene appears in every family whose root ancestor is reachable
via the union of vertical-parent edges and chimeric-donor edges.

Output files (oprefix taken from argv[3]):
{oprefix}.chimeras.gene_families
{oprefix}.chimeras.family_presence
{oprefix}.chimeras.pan_distribution
{oprefix}.chimeras.ancestry

The first three mirror the formats of get_pan_distrs.py outputs;
the fourth is a flat denormalized TSV listing every gene -> ancestor
edge (both vertical_parent and chimeric_donor rows).

Usage:
python3 get_pan_distrs_chimeric.py <prefix>.gene_parents <prefix>.chimeras.csv <output_prefix>
"""

import sys
import csv


# args
if len(sys.argv) != 4:
    sys.stderr.write(
        "usage: get_pan_distrs_chimeric.py "
        "gene_parents_file chimeras_csv_file output_prefix\n"
    )
    sys.exit(1)

gene_parents_file = sys.argv[1]
chimeras_csv_file = sys.argv[2]
oprefix = sys.argv[3]


# ---------------------------------------------------------------------------
# parse .gene_parents
# format: space-separated 4 ints per line:
#   child_genome_id child_gene_id parent_genome_id parent_gene_id
# the (-1, -1) sentinel marks a family root (genome-0 ancestral genes
# and HGT-acquired genes both use it).
# ---------------------------------------------------------------------------

gene_parents = {}
gene_list = set()
genome_list = set()

with open(gene_parents_file, "r") as f:
    for line in f:
        cc = line.strip().split(" ")
        if len(cc) < 4:
            continue
        ig = (int(cc[0]), int(cc[1]))
        og = (int(cc[2]), int(cc[3]))
        gene_parents[ig] = og
        gene_list.add(ig)
        gene_list.add(og)
        genome_list.add(int(cc[0]))
        genome_list.add(int(cc[2]))

genome_list.discard(-1)
gene_list.discard((-1, -1))


# ---------------------------------------------------------------------------
# parse .chimeras.csv into donors_of
# donors_of maps each acceptor gene -> list of (donor_gene, event_type).
# self-donor rows (donor == acceptor, e.g. INTRA sub-dup, INTRA inversion)
# are kept in this list so the ancestry dump can document them;
# the BFS below filters them out when computing families (they add
# no information and would just self-loop).
# ---------------------------------------------------------------------------

donors_of = {}

with open(chimeras_csv_file, "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        acc = (int(row["acceptor_genome_id"]), int(row["acceptor_gene_id"]))
        don = (int(row["donor_genome_id"]), int(row["donor_gene_id"]))
        et = row["event_type"]
        donors_of.setdefault(acc, []).append((don, et))


# ---------------------------------------------------------------------------
# multi-family membership via bfs. returns the set of family-root labels
# reachable from g via the union of vertical-parent and chimeric-donor edges.\
# visited-set handles cycles (notably MUTATION_INVERSION_INTER produces mutual
# donor edges between two genes in the same genome). self-donor edges are skipped.
# memo caches the result per starting gene; per-gene work is bounded by
# the number of nodes reachable from that gene.
# ---------------------------------------------------------------------------

def get_families(g, memo):
    if g in memo:
        return memo[g]
    families = set()
    visited = set()
    stack = [g]
    while stack:
        node = stack.pop()
        if node in visited:
            continue
        visited.add(node)
        p = gene_parents.get(node)
        if p == (-1, -1):
            families.add(f"family_{str(node[0])}_{str(node[1])}")
        elif p is not None:
            stack.append(p)
        for d, _et in donors_of.get(node, ()):
            if d == node:
                continue
            stack.append(d)
    memo[g] = families
    return families


family_to_genes = {}
family_to_genomes = {}
memo = {}

for g in gene_list:
    fams = get_families(g, memo)
    for f in fams:
        family_to_genes.setdefault(f, set()).add(g)
        family_to_genomes.setdefault(f, set()).add(g[0])


# ---------------------------------------------------------------------------
# output: .chimeras.gene_families  (same format as .gene_families)
# ---------------------------------------------------------------------------

family_list = sorted(family_to_genes.keys())
genomes_sorted = sorted(genome_list)

with open(f"{oprefix}.chimeras.gene_families", "w") as off:
    for f in family_list:
        off.write(f + " ")
        for g in sorted(family_to_genes[f]):
            off.write(f"({str(g[0])},{str(g[1])}) ")
        off.write("\n")


# ---------------------------------------------------------------------------
# output: .chimeras.family_presence  (same format as .family_presence)
# ---------------------------------------------------------------------------

with open(f"{oprefix}.chimeras.family_presence", "w") as off:
    off.write("# " + " genome_".join(str(i) for i in genomes_sorted) + "\n")
    for f in family_list:
        off.write(f + " ")
        for g in genomes_sorted:
            off.write("x " if g in family_to_genomes[f] else "- ")
        off.write("\n")


# ---------------------------------------------------------------------------
# output: .chimeras.pan_distribution  (same format as .pan_distribution)
# ---------------------------------------------------------------------------

pand = {}
for f, gs in family_to_genomes.items():
    c = len(gs)
    pand[c] = pand.get(c, 0) + 1

with open(f"{oprefix}.chimeras.pan_distribution", "w") as off:
    off.write("#genomes #families\n")
    if pand:
        for c in range(1, max(pand.keys()) + 1):
            off.write(f"{str(c)} {str(pand.get(c, 0))}\n")


# ---------------------------------------------------------------------------
# output: .chimeras.ancestry
# columns: genome_id  gene_id  relation  ancestor_genome_id  ancestor_gene_id  event_type
# rules:
#   - one vertical_parent row per gene that has an entry in gene_parents.
#     for family roots (including HGT genes) this row has ancestor (-1,-1)
#     and event_type "-", so the user can locate roots with a single filter.
#   - one chimeric_donor row per chimera contribution in chimeras.csv,
#     including self-donor rows (which document INTRA-* events). the user
#     can filter them out trivially (acceptor == donor).
# ---------------------------------------------------------------------------

with open(f"{oprefix}.chimeras.ancestry", "w") as off:
    off.write(
        "genome_id\tgene_id\trelation\tancestor_genome_id\tancestor_gene_id\tevent_type\n"
    )
    for g in sorted(gene_list):
        # vertical parent row (always emitted if gene has an entry,
        # even for roots where the row points at (-1, -1))
        p = gene_parents.get(g)
        if p is not None:
            off.write(
                f"{str(g[0])}\t{str(g[1])}\tvertical_parent\t"
                f"{str(p[0])}\t{str(p[1])}\t-\n"
            )
        # chimeric donor rows (one per contribution; preserves the
        # ordering of chimeras.csv, which is event_id-monotonic)
        for d, et in donors_of.get(g, ()):
            off.write(
                f"{str(g[0])}\t{str(g[1])}\tchimeric_donor\t"
                f"{str(d[0])}\t{str(d[1])}\t{et}\n"
            )
